### ISSUE TITLE
[Feature] Workout templates

### ISSUE THREAD

**Issue by Atrate** [Foxek/WiseTimer#3]
I feel like WiseTimer could have more appeal if it contained ready-made workout templetes, such as the 7 Minute Workout for beginners: https://well.blogs.nytimes.com/2013/05/09/the-scientific-7-minute-workout/

**Comment by Foxek** [comment]
At the moment, unfortunately, there is not enough time to implement such functionality. However, in the future it is possible

**Comment by Foxek** [comment]
But I do not mind if someone develops such features. The project is open and free and will remain so
